cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy

build_react:
  stage: build
  before_script:
    - yarn install
  script:
    - yarn build

deploy_s3_dev:
  stage: deploy
  dependencies:
    - build_react
  before_script:
    - pip install awscli # Install the AWS cli
  script:
    - yarn build:dev
  after_script:
    - tar -cvf build.tar build/ appspec.yml # upload only binary
    - aws s3 cp build.tar s3://iok-dev-gitlab/iok-administrator-react-dev-concrete/