# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3

pipelines:
  default:
    - step:
        name: Installing
        caches:
          - node
        script:
          - rm -rf package-lock.json
          - yarn
    - step:
        name: Build
        caches:
          - node
        script:
          - unset CI
          - yarn
          - yarn build:dev
          - mkdir deploy
        after-script:
          - tar -cvf deploy/build.tar build/ appspec.yml -C deploy # upload only binary
        artifacts:
          - deploy/**
    - step:
        name: Deploy to S3
        script:
          - pipe: atlassian/aws-s3-deploy:0.4.1
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              S3_BUCKET: 'iok-dev-gitlab/iok-administrator-react-dev-concrete'
              LOCAL_PATH: 'deploy'