export {HomePage} from './HomePage/HomePage';
export {NotFoundPage} from './NotFoundPage/NotFoundPage';
export {DashBoardPage} from './DashBoardPage/DashBoardPage';
export {ManagerPage} from './ManagerPage/ManagerPage';
export {CustomerPage} from './CustomerPage/CustomerPage';
export {SignInPage} from './SignInPage/SignInPage';
export {SitePage} from './SitePage/SitePage';
export {SitePlacePage} from './SitePlacePage/SitePlacePage';
export {ProductPage} from './ProductPage/ProductPage';
export {DeviceProfilePage} from './DeviceProfilePage/DeviceProfilePage'
export {DeviceHistoryPage} from './DeviceHistoryPage/DeviceHistoryPage';